name: alittlemore-infra-quality

x-quality-tool: &quality-tool
  read_only: true
  cap_drop:
    - ALL
  security_opt:
    - no-new-privileges:true
  tmpfs:
    - /tmp

services:
  trivy:
    <<: *quality-tool
    image: docker.io/aquasec/trivy:0.74.0@sha256:62b1e65e8869bc4b4c6aa4fa2b21595256c7c2f6018a9d9ad61caf87187c1969
    entrypoint:
      - trivy

  hadolint:
    <<: *quality-tool
    image: hadolint/hadolint:v2.15.1@sha256:32dac94127fd60b7b7e3fbfc65e1383b9b5e25c9bfd7b8536de7a539fe68a12d
    entrypoint:
      - hadolint
    network_mode: none

  shellcheck:
    <<: *quality-tool
    image: koalaman/shellcheck:v0.11.0@sha256:61862eba1fcf09a484ebcc6feea46f1782532571a34ed51fedf90dd25f925a8d
    entrypoint:
      - shellcheck
    network_mode: none
