APP_SECRET_KEY: ENC[AES256_GCM,data:HsYgnr9DH3vqbSjhHD93z1NSckz7QEFak5NpZAFp4Un/Ewqq2LfGwXy1VO/uT2sT7fdMHEmWkN2cXdgzG3nF9Q==,iv:/gEKZGxVEnmyRYEXtfoLndDMbpRa6DtAU3LaksWWM44=,tag:dhWIfr4nYiqntAyv+6eD/g==,type:str]
DB_PASSWORD: ENC[AES256_GCM,data:BRsoNVYJ37eUWH6dFrwuswAsMj6TsuGFEaVeuxjX6f5Vs1rNwPtZ1sdz3JjO4YXDRQsxgXkzjvapb1kxqdIdKg==,iv:w8Twrs106nHkfl7/y5I2ohtF19vLIfKWjM3rM+n1X+8=,tag:rmTr3Dkjl4TvRQEVbWJn9g==,type:str]
MINIO_ACCESS_KEY: ENC[AES256_GCM,data:ufnJLuyhCLhICs20wGkES/SVIzri3BqASKYLraTV2V5ZnUN6McbkqQ==,iv:J2t4kJKMUh4YSb4CHy4s+aG/kQXuCGlkVns+DCD2Td0=,tag:i4PYskDej5PgwddjrjvhfA==,type:str]
MINIO_SECRET_KEY: ENC[AES256_GCM,data:fM600FUPwVZoU1bG3fKM9FCgZ+26y76dNhOcrVksqK6aFiduUAfa32wnkgHjOm8EPkbRI1XxwsZ1+UAqLTH6gQ==,iv:uegIqGJDaiNbvZTlxxJ3+So3687cm4HqAa9dY/V0JSg=,tag:6dLpkmqBnf0l3iwgFXRVJQ==,type:str]
SENTRY_DSN: ENC[AES256_GCM,data:tV3WmZTIDPJ2l2HRYuX8s1gT6I39lsGuqAPyp4d4cibUpdcHHIBYcYBXeno8986PA8YUT4xgvHQ/+BwVhqGoubnAvE4zvJBXIwhteURq1LnZeKdek/u+UZQBqgT+iq4=,iv:ABYaSnTjCN5N3knwI59ZBjGv18L5p64t0ofV5qRZmPI=,tag:Ch2/F5qkaMj+5ah2WVjUIw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQck5kMGR3aHhGRkpoRndn
            QkxhK2tpY0RCTDFqcEZYTnBOYm5aMnZkR1VrClUzSlA0SkRCYVgvMmVXUDJWYU9C
            dVc3bWo5OUt1aVU3dkhDNUdhRWtUUkEKLS0tIEpuNGdvWGFZSTdhcjJMK3VXMVZp
            WFNyN0YwWjRaTjN3cjhsQitRU0NVRTgKG90dZ6icPn9QGo1NrRvFx17+7zKSyyPa
            87oCjGPFw/mdX5rwlCiaCFqyg/FvDziBjQVzohTzCsygoapvWHDIaA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1urx4m4hnwpjt5t53mzhmtdgm00qx57rzwxes4kzqkfvnxjqskals4g6jj8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvRmx5WnhFUEp4eXk5bkJC
            VWovZUoyUGFESklBelh3aTlBZEVXQ2xCaEdrCm4vTi9JRkRyd2QwMHFJbndGdktZ
            c2VvL3FJQXRnWG1sRm5GcUJrbGVPT1UKLS0tIGVFYUtRSFVOTGhiMFNScWZGNFpw
            THJ1bjFEWjYrY3ZITVByL0U2ZHRSNlkK2UX6ghbMUkgdzntYudhDAA37UGYThHQG
            hIuPP+dEFkjjJRt4XZS5J3E0+l0oElMpNVvrCJ7Vk65FO+UHgS2N3g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t9swap92mc799w578gtcewdrglt36zlt26gdp6lhm9hzxkrk7psszg4mtd
    lastmodified: "2026-09-18T20:16:31Z"
    mac: ENC[AES256_GCM,data:dLUIbAq4U42iaSBFVdr/zv9oozC76K3rsHlIZrTJcLxgQHkIdSqDy6CJZeO8NctWV+DXSucBiVTili93xPQlvj8kf5FWgUIUF4EXck3MZ40MnU0CW0KmRIeBxZMFrkuM0M1z8jRDK5mvqkI/zyAL3Ij7FvgX6fnGRyYhYqx59dA=,iv:vLTVgKuqEfh3VHWvZwRUxDsYJQAo2RHOLUwCkXGwpuc=,tag:kZbYDfnrMyUTukj67f+7yQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
