MINIO_ROOT_ACCESS_KEY: ENC[AES256_GCM,data:KOL3dcmSob3q7dG1WjBxbwm/0lIZE/90No8+SF35QYo4by+tgbUhAw==,iv:jmQEYG4/08MoFlADbZZagZlQe4YqglmveqEoLTEbkG8=,tag:k1k4vU1bTKgW+TRirbJyiw==,type:str]
MINIO_ROOT_SECRET_KEY: ENC[AES256_GCM,data:R3COunavLY3EpsDy6JAOew90ekQmJ7J9VfMoYPYwnQRscn5y3aiiUPwjCm3sELtqm7r47yAk6UEFWt80qOaQAQ==,iv:ZKsuEjKxD0wjTdq+2Fl08eXk7s2feVqOuh71c8RN4X4=,tag:3/1CPpkCGg3xxYy5bMLivg==,type:str]
DATABASUS_MINIO_ACCESS_KEY: ENC[AES256_GCM,data:TSzLyZZYQQYuJM1yYpT9LMPCh9UfhzRxEw7SgOJFtlxRwlnyaomYqQ==,iv:+SBaZsNfoRpTFLFJwWU2Gu12oRFiJMiW6gAJoE9yISo=,tag:HuGyJU3vj73BzwWkvrKgDA==,type:str]
DATABASUS_MINIO_SECRET_KEY: ENC[AES256_GCM,data:CvieyBV1ja4dKMvbPYsQTU//+AYx6VASHIUkVDUh1XXlssUM6+jpkbKcsLqteWdSHgalTseNrmmRA4j1Cz8IOA==,iv:xIlChXtUouj1XaihUT6NXc281qRBh8LoXgEVGSGz0vc=,tag:YHl8RUueJ+2kKFCK5sxlog==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUeVFTdEtZeXYxRDltSzB3
            OVg3WjVsQ0FmV05NM0tPWC9GUmVoM2tOT2dVCjAzUEd6U0dINFNDZ25qMTdCV0Q3
            VUo0elZJSC83TkZ0WE5RU3dqL1lRazQKLS0tIGpJakZhd0UwQjJDSjZpVnZMZ21a
            NU1lZUlseXhMeW5VNnRIQzRsemsrS0EK9kCTJdNBKIqmprI/TMR9UmE5kOVTrW7L
            hrk5EoMa8sJe3WSv+o0KM8gmSLAlc+5tERNXYG5e2eA5VoELln+VBg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1urx4m4hnwpjt5t53mzhmtdgm00qx57rzwxes4kzqkfvnxjqskals4g6jj8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxQXl0bmlxc29uU0ZiQVlS
            MXIzRFZtUkk5TUFITmdhLzU4L0dOOUNBdmtjClNFN3BmcDFZOC9CVTBIQ0JSbUxE
            ZzRjNnRnNFR5cGg1Z0wwL1g3UFVBNzgKLS0tIFJpcW9tWDhMRzl2cFhuQ2RjRmd3
            UnVtY1lscHRkRUtoOFdoem9veWNndVEKw0fgCT4a7eoIM7uAq09QIRMTkYuAk6Wl
            Ro6UeO8Ts8vhi+9mPz6I7KlI+384+DZFfLQ01uAl3i5QL0iGxLaCAA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t9swap92mc799w578gtcewdrglt36zlt26gdp6lhm9hzxkrk7psszg4mtd
    lastmodified: "2026-09-09T17:09:59Z"
    mac: ENC[AES256_GCM,data:FGS+137oA/HXRa/Rd0vok1FDiJqnudEO6JqkqNuTpF64IEx16Kyl9H2r3KqRkbI1ejE166tR6rKItnb7rNl7QKrBhO2R6vO6uB65XK43pgfBvYOfxXrnVHPHdQ7cC475+Ug4JCZFVOzyGloi+RQZzGu1IEC6UAmqhKdzzbJ8MLo=,iv:IeTnvEUiwr/+K7Gj2quWOqt9CClwISr3HaFoiuPdOIU=,tag:QGNOfbUq+ryl69Xt0HJpfw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
